# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/beyond2lte/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),beyond2lte)

$(call add-radio-file-sha1-checked,radio/cm.bin_SM-G975F,8596a7f7f59713ede5eae927ceaa854e61f4b6f3)
$(call add-radio-file-sha1-checked,radio/cm.bin_SM-G975N,65e81a09fff159bd0966863c04d41bb944731063)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-G975F,95a1958568d2aba8a6011665abf42a1b020e4263)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-G975N,420acfd16c44b8f1a4c874fd956ac035faed7539)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-G975F,5edaae899d26160bc988216bd40133e142d03756)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-G975N,7050bf8da51cc6105b0a5df209866faec22aa268)
$(call add-radio-file-sha1-checked,radio/models,72ac495a341828ede52406ecf89c0d9933b67dac)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-G975F,3c1824f9381a281711d99ed4c23b462c9cae4985)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-G975N,2c947e5902f5bef27e665ce942a1b9ef1b785361)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-G975F,33cdfacae0dcfd4645209d79b1a7168d4ecc6c5b)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-G975N,9820b66ffef1f3cc0f57e5e083c37bf567d9a054)
$(call add-radio-file-sha1-checked,radio/param.bin_SM-G975F,569d4cec352dada74fb2267c01eefe2c761e759f)
$(call add-radio-file-sha1-checked,radio/param.bin_SM-G975N,e5b2caa73a9b624fd5cf5be053330f8c3519d7aa)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-G975F,965855e998f60c8ae315f95960a0e70a27471c0c)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-G975N,019e96e7642dfc810b0f262bfa1f5a0ab16f4472)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-G975F,e52133d0c774154aa3060d1fc1560fa8466621df)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-G975N,f955a6f4ebf88121859c0600bd82790a0486b402)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-G975F,8732a680b732119ebba173845f1a943654cea764)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-G975N,c8079bd902d9cf3d79bbeae408f154e30d1398de)
$(call add-radio-file-sha1-checked,radio/version_SM-G975F,95f4123e7dd13a74814c75a6edd5bcbc72ef39c6)
$(call add-radio-file-sha1-checked,radio/version_SM-G975N,c7952bbf0de5e4b5600b1e005feaed4f69b56a4a)

endif
